### ISSUE TITLE
Zoneminder container forever waiting for MariaDB to start

### ISSUE THREAD

**Issue by ihor-chaban** [zoneminder-containers/zoneminder-base#14]
I tried to deploy your image on my RPI4 with Raspbian OS.
But as far as there is no official mariadb image for linux/arm/v7 architecture I tried to use linuxserver/mariadb image.
Everything seems fine, except for the one problem.
Your image wait for MariaDB start using s6-svwait
**etc/services.d/mariadb-configure/run:**
```
echo "Waiting for MariaDB to start" | info
# Wait for db to be up before configuring
/bin/s6-svwait -U /var/run/s6/services/mariadb
```
But the linuxserver image does not have s6-svwait integration so zoneminder container just waits forever.

I tried to change this code to
```
echo "Waiting for MariaDB to start" | info
# Wait for db to be up before configuring
while ! /bin/nc -z "${MYSQL_HOST}" 3306 do sleep 5; done
```
and rebuild the image, but the resulting image fails all the time, dunno why.
```
# docker logs -f zoneminder
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
```

Maybe you can suggest something or make your image independent from s6-svwait (as far as I can see it is used only for one purpose, which can be easily replaced)?
Also tried to run the image with biarms/mysql:5.7.30 image, it got working but "Got signal 11 (Segmentation fault), crashing" error appeared all the time after adding a monitor. Some googling bring me to the idea that the root of the issue is MySQL instead of MariaDB.

Any ideas are appreciated, as your image seem to be the most up-to-date and well assembled for linux/arm/v7, but because of the simple check everything is useless...

**Comment by alexyao2015** [comment]
The issue here is there is an uptime check that directly pings the sql server. If it's unreachable, perhaps by misconfiguration or not providing the correct user variables, it will wait until it goes up. 

Use the official mariadb image instead of the one by Linux server. The docker-compose files show how things should be ran.

https://github.com/zoneminder-containers/zoneminder-base/blob/851a5cdc18623b97e9c7051c4b7e01836e971006/root/etc/services.d/mariadb/data/check#L1

**Comment by ihor-chaban** [comment]
That's the point, the official mariadb image does not exist for arm32/v7, only for arm64/v8 https://hub.docker.com/_/mariadb?tab=tags.
That's why I faced this issue.
So looks like there are two options for arm32/v7: change the DB image to use s6 supervisor or change zoneminder image to get rid of s6 supervisor.

**Comment by alexyao2015** [comment]
You simply need to ensure the DB is accessible to the container by configuring the environment variables. If the container is not able to access the DB, its obviously going to hang waiting for the db to come online. The issue is not s6. The issue is a misconfiguration on your end.

**Comment by ihor-chaban** [comment]
Aha, I thought that the s6 should be injected into the source DB container as well.
Will try to find the reason on my end. Thank you for the fast reply.
