### ISSUE TITLE
Installed, not connecting

### ISSUE THREAD

**Issue by rrediske** [zoneminder-containers/zoneminder-base#15]
I had to tweak the yaml file by changing the version to 3.7 as version 3 does not support the format that the volumes are defined with (specifically the tmpfs volume). After that, docker-compose started without errors, but when I go to the server IP, http://192.168.33.31/, I get an nginx error, "502 Bad Gateway". The error from the docker terminal is:

zoneminder_1  | [nginx] 2021/09/01 14:39:06 [crit] 1501#1501: *4 connect() to unix:/run/php/php7.3-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.33.3, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "192.168.33.31"

I've setup a couple zoneminder servers in VM's, but this is my first container.

**Comment by rrediske** [comment]
When I shell into the container itself, I show run/php/php7.3-fpm.sock indeed does not exist, and instead /run/php/php7.4-fpm.sock is there. I'll poke around to see where I can point to that, but I only know enough to be dangerous, not really enough to knowingly fix things :)

**Comment by alexyao2015** [comment]
Should be fixed in this build. Try it after this build is complete. https://github.com/zoneminder-containers/zoneminder-base/actions/runs/1192386170

**Comment by rrediske** [comment]
Yup, it works! I got it working yesterday, just to test anyway. I made symbolic links from /run/php/php7.3-fpm.* to /run/php/php7.4-fpm.*   - I told you I knew just enough to be dangerous... 

I think I need to tweak a permission somewhere, it has a broken link to an icon: http://zoneminder/cgi-bin/nph-zms?scale=15&monitor=1&connkey=773609&rand=1630617064

but that's just cosmetic and I can fix that. I had a permissions problem on another zoneminder I installed, so I will poke around my notes from that server. It doesn't show a live feed, but I'm pretty sure that's because it's capturing h264 and firefox for linux doesn't support that codec. And I know it's working otherwise, as I can download the mp4's it capture and play them on VLC.

Thanks for all the hard work you do!

**Comment by alexyao2015** [comment]
Great! 

For your other question, it appears to work perfectly fine for me, and since I do not develop ZoneMinder itself, it would suggest you contact the ZoneMinder devs themselves about your issue through channels such as the Slack or the forums as I'm not equipt to answer ZoneMinder specific questions.
