### ISSUE TITLE
latest tagged?

### ISSUE THREAD

**Issue by gcormier** [zoneminder-containers/zoneminder-base#19]
Is there a way to specify the latest officially tagged versoin? Right now `latest` seems to be the latest build, 1.37.x.

I'm using `image: ghcr.io/zoneminder-containers/zoneminder-base:1.36.8`, but would love to get 1.36.10 when it comes out in a few days without updating my tags.

**Comment by alexyao2015** [comment]
Should be getting tagged to release and nightly now. Latest is pinned to the latest release version.
