### ISSUE TITLE
Hung processes

### ISSUE THREAD

**Issue by gcormier** [zoneminder-containers/zoneminder-base#20]
Discussion at https://github.com/ZoneMinder/zoneminder/issues/3375

It is suggested it might be an issue of the container specifically.

**Comment by alexyao2015** [comment]
Looking at the development of the story in the zoneminder issues, it appears that multiple other people are observing this same issue outside of this container. I'll put this issue on hold for now until some more conclusive evidence is obtained.

**Comment by alexyao2015** [comment]
I think this was fixed by zm.
