### ISSUE TITLE
Enabling HTTPS

### ISSUE THREAD

**Issue by kkemenes** [zoneminder-containers/zoneminder-base#21]
Even though I've set the ports in the docker compose file, I'm getting Unable to connect error when trying to access Zoneminder through https. I have keys generated but I'm not sure how to configure the server in the container to use them

**Comment by alexyao2015** [comment]
Native https isn't supported by this container. Either use the eventserver container with native https support or better yet, simply use a reverse proxy such as traefik, caddy, etc.

If you really want to use native ssl here, see the changes done to the eventserver container and apply them here.

**Comment by kkemenes** [comment]
I managed to get it working. Thanks for helping
