### ISSUE TITLE
Help run

### ISSUE THREAD

**Issue by GrewOZ** [zoneminder-containers/zoneminder-base#24]
I have a device - TerraMaster F4-210 (ARM V8 64-bit quad-core processor, a frequency of up to 1.4 GHz and 2GB RAM)

Docker is installed on it.

I download and install your application. It starts up and runs. I can’t connect to it. The IP address is not available.

Can you help me with something?

Thanks!

**Comment by GrewOZ** [comment]
> I have a device - TerraMaster F4-210 (ARM V8 64-bit quad-core processor, a frequency of up to 1.4 GHz and 1GB RAM)
> 
> Docker is installed on it.
> 
> I download and install your application. It starts up and runs. I can’t connect to it. The IP address is not available.
> 
> Can you help me with something?
> 
> Thanks!

**Comment by alexyao2015** [comment]
Logs

**Comment by GrewOZ** [comment]
<html>
<body>


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
--
14:53:27 | [s6-init] ensuring user provided files have correct perms...exited 0.
14:53:27 | [fix-attrs.d] applying ownership & permissions fixes...
14:53:27 | [fix-attrs.d] done.
14:53:27 | [cont-init.d] executing container initialization scripts...
14:53:27 | [cont-init.d] 00-reconfigure-user.sh: executing...
14:53:27 | 2021-12-20 08:53:27.250939365 [reconfigure-user] INFO Setting permissions for user www-data
14:53:27 | 2021-12-20 08:53:27.356335587 [reconfigure-user] INFO Setting permissions for user nobody at /log
14:53:27 | [cont-init.d] 00-reconfigure-user.sh: exited 0.
14:53:27 | [cont-init.d] 10-log-config.sh: executing...
14:53:27 | 2021-12-20 08:53:27.472483513 [log-config] INFO Configuring log rotation with a maximum of 10 logs and a max log size of 1000000 bytes
14:53:27 | [cont-init.d] 10-log-config.sh: exited 0.
14:53:27 | [cont-init.d] 20-system-config.sh: executing...
14:53:27 | 2021-12-20 08:53:27.701899216 [system-config] INFO Setting system timezone to America/Chicago
14:53:27 | 2021-12-20 08:53:27.711639031 [system-config] INFO Configuring PHP Time
14:53:28 | 2021-12-20 08:53:28.579538290 [system-config] INFO Applying PHP Optimizations
14:53:28 | 2021-12-20 08:53:28.766124512 [system-config] INFO Redirecting PHP Logs to stdout
14:53:28 | [cont-init.d] 20-system-config.sh: exited 0.
14:53:28 | [cont-init.d] 30-zm-config.sh: executing...
14:53:28 | 2021-12-20 08:53:28.893333882 [zm-config] FIRSTRUN Configuring ZoneMinder Configuration folder
14:53:28 | 2021-12-20 08:53:28.938024104 [zm-config] FIRSTRUN Configuring ZoneMinder Data folder
14:53:28 | 2021-12-20 08:53:28.956001586 [zm-config] INFO Configuring ZoneMinder db Settings
14:53:29 | [cont-init.d] 30-zm-config.sh: exited 0.
14:53:29 | [cont-init.d] 40-msmtp-config.sh: executing...
14:53:29 | 2021-12-20 08:53:29.087649993 [msmtp-config] INFO Configuring msmtp settings...
14:53:29 | [cont-init.d] 40-msmtp-config.sh: exited 0.
14:53:29 | [cont-init.d] 50-nginx-config.sh: executing...
14:53:29 | 2021-12-20 08:53:29.197821808 [nginx-config] INFO Configuring nginx settings...
14:53:29 | [cont-init.d] 50-nginx-config.sh: exited 0.
14:53:29 | [cont-init.d] ~-socklog: executing...
14:53:29 | [cont-init.d] ~-socklog: exited 0.
14:53:29 | [cont-init.d] done.
14:53:29 | [services.d] starting services
14:53:29 | [services.d] done.
14:53:29 | [mariadb-configure] 2021-12-20 08:53:29.868970696 INFO Waiting for MariaDB to start
14:53:29 | [nginx] 2021-12-20 08:53:29.861252141 INFO Waiting for ZoneMinder to start
14:53:29 | [php-fpm] 2021-12-20 08:53:29.826005178 INFO Starting PHP-fpm...
14:53:29 | [fcgiwrap] 2021-12-20 08:53:29.834948733 INFO Starting fcgiwrap...
14:53:29 | [mariadb] 2021-12-20 08:53:29.866325919 INFO Waiting for Mariadb to start
14:53:29 | [zoneminder-service] 2021-12-20 08:53:29.878731770 INFO Waiting for MariaDB to start
14:53:30 | 2021-12-20 08:53:30.070188548 listening on /dev/log, gid=65534, uid=65534, starting.


</body>
</html>

**Comment by alexyao2015** [comment]
The logs are pretty clear that the issue is waiting for mariadb to start. Suggest reading the readme again and following it step by step.

**Comment by GrewOZ** [comment]
This is my first time dealing with docker. Thank you. I understand. If you can direct me specifically, I will be grateful.

**Comment by GrewOZ** [comment]
started the database ...
