### ISSUE TITLE
Got an error reading communication packets

### ISSUE THREAD

**Issue by Chinostu** [zoneminder-containers/zoneminder-base#25]
Hello, i'm trying to get the Zoneminder container working in a Raspberry Pi, OS: Debian 11 bullseye, Kernel: aarch64 Linux 5.10.63-v8+.
I followed every step in the readme file, many times, and always getting the same error when trying to connect to the Zoneminder web page, it shows 404 Not Found.
The only thing I changed in the .env file was the timezone, I did not touch the rest.

When seeing the logs in portainer I get this for the zoneminder container:
[nginx] 2021/12/29 17:06:03 [error] 1161#1161: *1 open() "/var/www/html/zm" failed (2: No such file or directory), client: 192.168.1.100, server: , request: "GET /zm HTTP/1.1", host: "192.168.1.14"
[nginx] 192.168.1.100 - - [29/Dec/2021:17:06:03 -0300] "GET /zm HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"

And when I restart the zoneminder container, the mariadb container log shows:
2021-12-29 17:10:06 50 [Warning] Aborted connection 50 to db: 'zm' user: 'mysqluser' host: '172.20.0.3' (Got an error reading communication packets)

What am I doing wrong?
Thank you in advance

![error](https://user-images.githubusercontent.com/96428799/147699931-cf88134e-89aa-4025-b6b9-8b3361d9fe88.jpg)

**Comment by alexyao2015** [comment]
Don't access it at /zm

**Comment by Chinostu** [comment]
You just blew my mind

Thank you
