### ISSUE TITLE
cannot pull library/mariadb

### ISSUE THREAD

**Issue by YuriMri** [zoneminder-containers/zoneminder-base#33]
Hello,
I'm trying to get this running on Raspberry pi 4B (32-bit) and after I try to run `docker-compose up -d`
I get:
```
Pulling db (mariadb:)...
latest: Pulling from library/mariadb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```
I notice there is warning in yaml file:
```
  # !! WARNING: !!
  # If using linuxserver/mariadb, you will need to add
  # skip-log-bin to mysqld and disable all log_bin options
```
but I cannot find <kbd>mysqld</kbd> file or folder.

I'm not linux pro but I already have multiple other containers on raspberries in my environment.

I will be very happy if someone can point me in the right direction as this project would help me a lot.
Thank you

**Comment by alexyao2015** [comment]
#22 should help you with this issue
