### ISSUE TITLE
How to use multi-server?

### ISSUE THREAD

**Issue by Anonymous-User47** [zoneminder-containers/zoneminder-base#45]
So you said "There is also full support for multi-server setups with automation to link all servers!" but how would i auto-link them?
Do the other servers need to be built on the multi .yml as well or just the regular?
I know this is more of a ZM question but can servers make monitors fed from the camera feeds from other servers?
And how would I connect servers over WAN?

**Comment by alexyao2015** [comment]
I believe you just need to set `ZM_SERVER_HOST` to the address of the second server.
