### ISSUE TITLE
Bullseye (11) -> Bookworm (12)

### ISSUE THREAD

**Issue by Simpler1** [zoneminder-containers/zoneminder-base#52]
Are there plans to move from Debian bullseye (11) to bookworm (12) so that janus can be installed and configured?

Reference:
https://www.youtube.com/watch?v=otAVgAMSUB8

**Comment by alexyao2015** [comment]
I'm not opposed to changing the base image, but I don't know if it'll work without any additional changes. I'll accept a PR if one is made. Otherwise, as mentioned in the readme, I don't use this project and I don't have the capacity to spend a bunch of my time on it.

**Comment by alexyao2015** [comment]
Done
