### ISSUE TITLE
Customizing MariaDB port

### ISSUE THREAD

**Issue by armond-avanes** [zoneminder-containers/zoneminder-base#57]
Hello.

I can't find any documentation on using a custom port number for MariaDB. I have an existing database server instance running on a port other than the default 3306. But I can't find any environment variable to set the port on my Zoneminder docker run. I'll appreciate if anyone can help me.

Thanks.

**Comment by jeremysherriff** [comment]
From what I can see of the config files, you simply edit the [.env file](https://github.com/zoneminder-containers/zoneminder-base/blob/4b5f5899f513ea3bc92e14064e62ffdc305b929a/.env#L16) and set the host:port as necessary.
