### ISSUE TITLE
Licensing issues pertaining to the docker image as the repo is copyright with no license file.

### ISSUE THREAD

**Issue by baudneo** [zoneminder-containers/zoneminder-base#65]
Since your repo does not have a license, users cannot fork and build off of your code. However, docker image licensing is quite different.

It is my understanding I can use a docker image as a base image in a multi image build even if the repo does not have a license. This is because the software you are packaging in the docker image are OSS licensed software (nginx, zoneminder, mariadb).

I am here asking for clarification of your licensing terms. Obviously the repo (dockerfile) is copyright to you but the image is up for debate. I would prefer your blessing to use the image as a base image in a multi image build. This is for the new ML system, I would like to install the client side libs on top of your image. The resulting dockerfile will be licensed as MIT or GPL (dependent on any issues with ZM's license).

I look forward to your response.

**Comment by baudneo** [comment]
Guess ill use the image to build off of without your blessing.

**Comment by alexyao2015** [comment]
Sorry about the delay. Feel free to build off of this image.

**Comment by baudneo** [comment]
Awesome, thank you for your blessing!
