### ISSUE TITLE
maximum number of cameras per 1 node

### ISSUE THREAD

**Issue by Lsdshnik** [zoneminder-containers/zoneminder-base#66]
Good afternoon, I used your docker-compose and successfully deployed docker with zoneminder, blocked the creation of a container with a database in compos and deployed it separately. The problem is that I have a lot of cameras and if I add 25 cameras, then everything works fine, but after adding 26 cameras and further, they simply do not work (if I move them to 2 nodes, then they start working), as a result of the fact that I have a lot of cameras, I get at least 1 node 30-40 cameras. What could this be related to? how to solve this problem?
![image](https://github.com/zoneminder-containers/zoneminder-base/assets/89648583/43ee1e0b-8b22-411d-8efa-09b787addfcf)

**Comment by connortechnology** [comment]
I'm guessing you are out of space in /dev/shm.  You likely didn't allocate enough in the compose.
