### ISSUE TITLE
docker-compose - login error during start

### ISSUE THREAD

**Issue by yayaasd** [zoneminder-containers/zoneminder-base#67]
I am trying to run the docker compose, but stuck at the given error which is repeating every second:
`57 30 [Warning] Access denied for user '-p'@'172.23.0.3' (using password: NO)`

I just copy&paste the docker-compose file, only edited:
- Folders to map
- port of webui

everything else is default. Any Ideas?

**Comment by yayaasd** [comment]
Update: 
also set the .env file with needed config:
`MYSQL_ROOT_PASSWORD=pass
MYSQL_USER=user
MYSQL_PASSWORD=pass

TZ=Europe/Zurich

MAX_LOG_SIZE_BYTES=1000000
MAX_LOG_NUMBER=20`

but even the login to mysql is not working.
also checked the **zm.conf** file - the user + pass is given in that file...

**Comment by alexyao2015** [comment]
Seems that you didn't configure docker to use the environment variables in .env
